### ISSUE TITLE
Why there are so many bugs ????

### ISSUE THREAD

**Issue by quqxui** [DeepGraphLearning/RNNLogic#16]
What are the requirements？

Make sure the codes work fine before uploading.

**Comment by mnqu** [comment]
You can find the requirements in the attached file. We are sorry that the codes were refactored for several times, so they look a little bit messy. For convenience, please consider using the codes of RNNLogic+. Thanks!
[py37.txt](https://github.com/DeepGraphLearning/RNNLogic/files/9089923/py37.txt)
