### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by wead-hsu** [DeepGraphLearning/RNNLogic#3]
hi. meng. I have tried to run the code (main branch), however, it reports the segment error in gpu. After debugging, it turns out that the error occurs in the rule_embed function. I am not very familiar with the CUDA, so I do not know how to fix this issue (I do not whether this issue is encountered only by me). 
But I can run the code in torch branch.

**Comment by wead-hsu** [comment]
> hi. meng. I have tried to run the code (main branch), however, it reports the segment error in gpu. After debugging, it turns out that the error occurs in the rule_embed function. I am not very familiar with the CUDA, so I do not know how to fix this issue (I do not whether this issue is encountered only by me).
> But I can run the code in torch branch.

After comparing the codes in torch and main branches, I realize it is due to the difference in the dataset. kinship_325 is ok but kinship is not. Their difference is about reverse relations. I have not found the reason why the code fails.

**Comment by mnqu** [comment]
Hi Wead, thanks for pointing it out! The error was caused by some format issues in the dataset. We have fixed the problem, and now you should be able to run with the kinship dataset in the main branch.

Meng

**Comment by wead-hsu** [comment]
> Hi Wead, thanks for pointing it out! The error was caused by some format issues in the dataset. We have fixed the problem, and now you should be able to run with the kinship dataset in the main branch.
> 
> Meng

Thanks for your quick response!
